name: composite-actions-using-vars

on:
  workflow_dispatch:

jobs:
  test-composite-action:
    runs-on: ubuntu-latest
    steps:
      - name: test-composite-action
        uses: ./.github/actions/referencing-vars