name: if-with-booleans-in-workflow

on: 
  workflow_dispatch:
    inputs:
      boolean_input:
        description: "A boolean input"
        required: false
        type: boolean
        default: false

jobs:
  test-boolean-input:
    runs-on: ubuntu-latest
    steps:
    - name: Test input as boolean true
      if: ${{ inputs.boolean_input == true }}
      run: |
        echo "Input was: ${{ inputs.boolean_input }}"
        echo "Executing the true step"

    - name: Test input as boolean false
      if: ${{ inputs.boolean_input == false }}
      run: |
        echo "Input was: ${{ inputs.boolean_input }}"
        echo "Executing the false step"

    - name: Test input as strings true
      if: ${{ inputs.boolean_input == 'true' }}
      run: |
        echo "Input was: ${{ inputs.boolean_input }}"
        echo "Executing the 'true' step"

    - name: Test input as strings false
      if: ${{ inputs.boolean_input == 'false' }}
      run: |
        echo "Input was: ${{ inputs.boolean_input }}"
        echo "Executing the 'false' step"
